#!/bin/bash

# Here we start by converting GDMA multipoles to MDCM format, then we generate
# a gaussian-format cube file containing MEP points generated by the multipoles, then
# we compare the multipolar MEP to the reference (DFT) MEP for points outside the
# molecular surface and within a fixed cutoff (hard-coded in pcubefit.x)

ROOT=/home/devereux/eric/esp_gdma_grid
WORKDIR=$ROOT
BINDIR=$WORKDIR/bin
REFDIR=$WORKDIR/ref
SYSNAME=acrolein_1200
PUNCHFILE=$REFDIR/$SYSNAME.pun  # GDMA punch file to convert
PCUBE=$REFDIR/$SYSNAME.chk.fchk.potential.cube  # reference (DFT) MEP cube file (gaussian 09 format)
DCUBE=$REFDIR/$SYSNAME.chk.fchk.density.cube # reference (DFT) density cube file
MTPFILE=$WORKDIR/$SYSNAME.mdcm.mtp    # name for MDCM format multipole file that will
                                      # be generated

# convert GDMA punch file to MDCM file format:
cd $WORKDIR
./src/pun2mdcm.pl $PUNCHFILE
mv converted.dat $MTPFILE

# generate cube file from MDCM multipole file
$BINDIR/pcubefit.x -v -generate -multipole -esp $PCUBE -dens $DCUBE -xyz $MTPFILE

# compare the cube file from GDMA multipoles with the reference DFT file
$BINDIR/pcubefit.x -v -analysis -esp $PCUBE -esp2 $WORKDIR/*_expansion.cube -dens $DCUBE

## Test section only: compare CHARMM cube with cube from GDMA
##PCUBE=/home/devereux/eric/esp_charmm_grid/charmm/charmm.cube
##$BINDIR/pcubefit.x -v -analysis -esp $PCUBE -esp2 $WORKDIR/*_expansion.cube -dens $DCUBE

