#!/bin/bash

# Here we start by converting GDMA multipoles to MDCM format, then we generate
# a gaussian-format cube file containing MEP points generated by the multipoles, then
# we compare the multipolar MEP to the reference (DFT) MEP for points outside the
# molecular surface and within a fixed cutoff (hard-coded in pcubefit.x)

# WARNING: GDMA punch file and both cube files should be generated from the same
# QM calculation to ensure that all coordinates and atom ordering are consistent

# FOLDERS
ROOT=$HOME/MDCM-git/examples/naptha/
WORKDIR=$ROOT/1-mtp-cube
BINDIR=$HOME/MDCM-git/bin
REFDIR=$ROOT/ref
# INPUT
PUNCHFILE=$REFDIR/gdma-l4.punch  # GDMA punch file to convert
PCUBE=$REFDIR/naphta.pot.cube  # reference (DFT) MEP cube file (gaussian 09 format)
DCUBE=$REFDIR/naphta.dens.cube # reference (DFT) density cube file
# OUTPUT
MTPFILE=$WORKDIR/gdma-l4.dat    # MDCM format multipole file

# convert GDMA punch file to MDCM file format:
cd $WORKDIR
$BINDIR/pun2mdcm.pl $PUNCHFILE
mv converted.dat $MTPFILE

# generate cube file from MDCM multipole file
$BINDIR/pcubefit.x -v -generate -multipole -esp $PCUBE -dens $DCUBE -xyz $MTPFILE

# compare the cube file from GDMA multipoles with the reference DFT file
$BINDIR/pcubefit.x -v -analysis -esp $PCUBE -esp2 $WORKDIR/hexadecapole_expansion.cube -dens $DCUBE

