#!/bin/bash

# In this step we run a differential evolution fit for each fragment. 5
# separate fits are performed here, for each fit we try fitting models with
# between MINFRAGCHG and MAXFRAGCHG charges per fragment. The reference ESP 
# used for fitting is generated by the atomic multipoles. 

# Note: adapt the Slurm script below to whatever cluster environment you're using

# FOLDERS
ROOTDIR=/home/devereux/MDCM-release/examples/fragment-fit
WORKDIR=$ROOTDIR/3-fit-fragments
BINDIR=/home/devereux/MDCM-release/bin
REFDIR=$ROOTDIR/../ref
ATOMDIR=$ROOTDIR/2-fit-atoms
# INPUT
MTPFILE=$ROOTDIR/1-mtp-fit/fitted-mtpl.dat # from step 2
PCUBE=$REFDIR/benzene-pot.cube 
DCUBE=$REFDIR/benzene-dens.cube
# FITTING PARAMETERS
NFIT=5       # number of separate fits to perform for each fragment (should not exceed atom fits)
NTRY=3         # number of tries for each fit
MAXATMCHG=4    # max charges per atom used in atom fits
NFRAG=2        # number of fragments to fit
MINFRAGCHG=6   # smallest number of charges to fit for fragment
MAXFRAGCHG=12  # largest number of charges to fit for fragment
ATOMLIST=("1,2,3,7,8,9" "4,5,6,10,11,12") # array of atom indices of each fragment


cd $WORKDIR

for ((i=1; i<=$NFRAG; i++)); do
  cd $WORKDIR
  ii=$(($i-1))
  mkdir -p "frag"$i && cd "frag"$i

  for ((j=1; j<=$NFIT; j++)); do
    cd $WORKDIR"/frag"$i
    mkdir -p fit$j && cd fit$j
    cp $ATOMDIR/fit$j/*xyz .  # copy atom fit results used to build starting population
  
    for ((k=$MINFRAGCHG; k<=$MAXFRAGCHG; k++)); do
      SCRIPT=$k"chgs.sh"
      NCHG=$k
      echo "#!/bin/bash

#SBATCH --job-name=frag${i}fit${j}q${k}
#SBATCH --nodes=1
#SBATCH --ntasks=8
#SBATCH --partition=long

WORKDIR=$WORKDIR
BINDIR=$BINDIR
REFDIR=$REFDIR
MTPFILE=$MTPFILE
PCUBE=$PCUBE
DCUBE=$DCUBE
NTRY=$NTRY
ATOMLIST=\"${ATOMLIST[$ii]}\"
MINCHG=$NCHG
MAXCHG=$NCHG
NAME="${k}chgs"

cd $WORKDIR/frag$i/fit$j

echo frag${i}fit${j}q${k}
hostname

\$BINDIR/pcubefit.x -greedy -mtpfile \$MTPFILE -esp \$PCUBE -dens \$DCUBE -ncmin \$MINCHG -ncmax \$MAXCHG -atom \$ATOMLIST -nacmax 4 -ntry \$NTRY -v > \$NAME".out"
" > $SCRIPT

      sbatch $SCRIPT
      sleep 1
    done
  done
done

